name: Branch Compilation

on:
  workflow_dispatch:
    inputs:
      java-version:
        description: 'the java version to compile with'
        required: true
        default: '11'
      maven-version:
        description: 'the maven version to compile with'
        required: true
        default: '3.8.1'
      starting-project:
        description: 'the project to start the job with (it is normally the latest leaf from the tree)'
        required: true
        default: 'kiegroup/kie-wb-distributions'

jobs:
  build-chain:
    concurrency:
      group: pull_request-${{ github.head_ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    name: Maven Build
    steps:
      - name: script
        shell: bash
        run: printenv
      - name: Build Chain
        uses: kiegroup/droolsjbpm-build-bootstrap/.ci/actions/build-chain@compilation
        with:
          definition-file: https://raw.githubusercontent.com/kiegroup/droolsjbpm-build-bootstrap/main/.ci/compilation-config.yaml
          starting-project: ${{ github.event.inputs.starting-project }}
          annotations-prefix: ${{ runner.os }}-${{ github.event.inputs.java-version }}/${{ github.event.inputs.maven-version }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          flow-type: branch
          logger-level: debug
