name: Build Chain (Test)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'LICENSE*'
      - '.gitignore'
      - '*.md'
      - '*.txt'
      - 'docs/**'
      - 'ide-configuration/**'
      - 'script/**'
  issue_comment:
    types: [created]


jobs:
  build-chain:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [8]
        maven-version: ['3.8.1']
      fail-fast: true  
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo comment body
        if: github.event.comment
        run: echo ${{ github.event.comment.body }}
      - name: Echo comment pull_request
        if: github.event.pull_request
        run: echo ${{ github.event.pull_request.id }}
        
          
