name: Build Chain

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'LICENSE*'
      - '.gitignore'
      - '*.md'
      - '*.txt'
      - 'docs/**'
      - 'ide-configuration/**'
      - 'script/**'
  issue_comment:
    types: [created]

jobs:
  build-chain:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo comment body
        if: github.event.comment
        run: echo ${{ github.event.comment.body }}
      - name: Echo comment pull_request
        if: github.event.pull_request
        run: echo ${{ github.event.pull_request.id }}
        
          
